Nborovic 8 react
m-luketin/Retrovizor pull request #6
Opened 2019-08-06 19:35 UTC by nborovic

2019-08-06 20:17 UTC, Lnola approved these changes
Me likey

2019-08-06 20:18 UTC, Lnola requested changes
Me see conflicts. Fix pls

2019-08-06 21:50 UTC, m-luketin approved these changes
Also ne kuzin di su konflikti, Pls fix.

2019-08-07 12:18 UTC, Lnola approved these changes

2019-08-07 20:50 UTC, merged